# Generated by Django 2.2.9 on 2020-02-10 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('times_slot', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Classs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('order', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'online'), (2, 'dist_program'), (3, 'offline')], default=1)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClassPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('student_id', models.IntegerField()),
                ('current', models.IntegerField(choices=[(0, 'Zero'), (1, 'One')], default='0')),
                ('status', models.BooleanField(blank=True, default=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentclasses', to='institute.Classs')),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institute.Programs')),
            ],
        ),
        migrations.CreateModel(
            name='SessionHasProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionprogram', to='institute.Programs')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='institute.Sessions')),
            ],
        ),
        migrations.CreateModel(
            name='Programhasclasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programclassid', to='institute.Classs')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_list', to='institute.Programs')),
            ],
        ),
        migrations.CreateModel(
            name='Programclasshassubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(verbose_name='created Date')),
                ('class_has_subjects_id', models.IntegerField()),
                ('program_has_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_class', to='institute.Programhasclasses')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseHasSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_program', to='institute.Sessions')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyHasBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('student_id', models.IntegerField()),
                ('faculties', models.IntegerField()),
                ('batches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculybatches', to='institute.Batches')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='batches',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batchphase', to='institute.PhaseHasSession'),
        ),
    ]
