# Generated by Django 2.2.9 on 2020-02-10 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='phasehassession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='programclasshassubjects',
            name='class_has_subjects_id',
        ),
        migrations.AddField(
            model_name='phasehassession',
            name='program_session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='phase_session', to='institute.SessionHasProgram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programclasshassubjects',
            name='class_has_subjects',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject_has_unit', to='subjects.SubjectHasUnit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionhasprogram',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_has_program', to='institute.Sessions'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_programs', to='institute.Programs'),
        ),
        migrations.AddField(
            model_name='programs',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='target_name', to='institute.Target'),
            preserve_default=False,
        ),
    ]
