# Generated by Django 2.2.9 on 2020-02-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_auto_20200210_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='program',
        ),
    ]
