# Generated by Django 2.2.9 on 2020-02-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_remove_sessions_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='session_programs', to='institute.Programs'),
            preserve_default=False,
        ),
    ]
