# Generated by Django 2.2.9 on 2020-02-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_sessions_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='program',
        ),
    ]
