# Generated by Django 2.2.9 on 2020-02-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(1, 'Deleted'), (0, 'Active')], default=0)),
                ('type', models.SmallIntegerField(choices=[(0, 'Notes'), (1, 'Video')], default=0)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('downloadable', models.BooleanField(default=False)),
                ('faculty_only', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyMaterialTOCMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(1, 'Deleted'), (0, 'Active')], default=0)),
                ('level', models.SmallIntegerField(choices=[(0, 'Unit'), (1, 'Chapter'), (2, 'Topic'), (3, 'Subtopic')])),
                ('toc_id', models.IntegerField()),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toc', to='content.StudyMaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyMaterialFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='study_material/')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.Language')),
                ('study_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.StudyMaterial')),
            ],
        ),
    ]
