# Generated by Django 2.2.9 on 2020-02-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterHasTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_code', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectHasUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('order', models.IntegerField()),
                ('book_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicHasContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('content', models.IntegerField(choices=[(1, 'lecture'), (2, 'studymaterial'), (3, 'video'), (4, 'doubtclass'), (5, 'doubtclass'), (6, 'practice problems'), (7, 'eal test'), (8, 'practice test'), (9, 'online class')], default=1)),
                ('type', models.IntegerField(choices=[(1, 'unit'), (2, 'chapter'), (3, 'chapter'), (4, 'sub-topics')], default=1)),
                ('type_id', models.IntegerField(choices=[(1, 'unit'), (2, 'chapter'), (3, 'chapter'), (4, 'sub-topics')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='UnitHasChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('order', models.IntegerField()),
                ('subject_has_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.SubjectHasUnit')),
            ],
        ),
        migrations.CreateModel(
            name='TopicHasSubtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'N')], default=5)),
                ('chapter_has_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.ChapterHasTopic')),
            ],
        ),
        migrations.CreateModel(
            name='HasSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(max_length=200)),
                ('master_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.MasterSubjects')),
            ],
        ),
        migrations.AddField(
            model_name='chapterhastopic',
            name='unit_has_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.UnitHasChapter'),
        ),
    ]
