# Generated by Django 2.2.9 on 2020-02-11 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0002_subjecthasunit_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterhastopic',
            name='unit_has_chapter',
        ),
        migrations.RemoveField(
            model_name='topichascontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='topichascontent',
            name='type',
        ),
        migrations.RemoveField(
            model_name='topichascontent',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='topichassubtopic',
            name='chapter_has_topic',
        ),
        migrations.RemoveField(
            model_name='unithaschapter',
            name='subject_has_unit',
        ),
        migrations.AddField(
            model_name='chapterhastopic',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapterhastopic',
            name='unit_has_chapter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.UnitHasChapter'),
        ),
        migrations.AddField(
            model_name='topichascontent',
            name='content_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topichascontent',
            name='content_type',
            field=models.IntegerField(choices=[(1, 'notes'), (2, 'video'), (3, 'assessments')], default=0),
        ),
        migrations.AddField(
            model_name='topichascontent',
            name='faculty_releasable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topichascontent',
            name='toc_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topichascontent',
            name='toc_level',
            field=models.IntegerField(choices=[(1, 'unit'), (2, 'chapter'), (3, 'chapter'), (4, 'sub-topics')], default=0),
        ),
        migrations.AddField(
            model_name='topichassubtopic',
            name='label',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unithaschapter',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unithaschapter',
            name='subject_has_unit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.HasSubjects'),
        ),
        migrations.AlterField(
            model_name='chapterhastopic',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterhastopic',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chapterhastopic',
            name='order',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subjecthasunit',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topichascontent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topichascontent',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topichassubtopic',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topichassubtopic',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topichassubtopic',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topichassubtopic',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unithaschapter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unithaschapter',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unithaschapter',
            name='order',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TocHasContentReleasedByFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.BigIntegerField(default=0)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('toc_has_content_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.TopicHasContent')),
            ],
        ),
        migrations.CreateModel(
            name='LectureHasContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.BigIntegerField(default=0)),
                ('toc_has_content_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.TopicHasContent')),
            ],
        ),
    ]
