# Generated by Django 2.2.9 on 2020-02-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20200211_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersubjects',
            name='background_code',
            field=models.CharField(default='#0000FF', max_length=10),
        ),
        migrations.AddField(
            model_name='mastersubjects',
            name='url',
            field=models.ImageField(default='', upload_to='subjects/'),
            preserve_default=False,
        ),
    ]
