# Generated by Django 2.2.9 on 2020-02-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='student/profile/'),
            preserve_default=False,
        ),
    ]
